---
application:
    name: 'reduced'
    project: 'Reduced'
    organization: 'QoveryCommunity'
    publicly_accessible: true
    port: 8080

routers:
    - name: 'main-reduced'
      custom_domains:
          - branch: master
            domain: reduced.me
      routes:
          - application_name: 'reduced'
            paths:
                - '/*'
