---
application:
    name: 'reduced'
    project: 'Reduced'
    organization: 'QoveryCommunity'
    publicly_accessible: true
    port: 8080
    custom_domains:
        - branch: master
          domain: reduced.me
routers:
    - name: 'main-reduced'
      routes:
          - application_name: 'reduced'
            paths:
                - '/*'
