---
application:
    name: 'reduced'
    project: 'Reduced'
    organization: 'QoveryCommunity'
    publicly_accessible: true
    port: 80
routers:
    - name: 'main-reduced'
      routes:
          - application_name: 'reduced'
            paths:
                - '/*'
